/**
 * PROGRAM GELISIM SEYRI-GENEL GOREVLER-ACIKLAMALAR
 * VERSIYON 101_2 OZELLIKLERI
 * RESEN YAPILANLAR
 * 4 MAYIS 2008 ITIBARIYLE: TEKLIF EKLEME, TEKLIF LISTELEM FONKSIYONLARI BASARILI OLARAK HAZIRLANDI
 * 4 MAYIS 2008 2:        : TUM TABLOLAR UZERINDAN VERI SECIMI FONKSIYONU YAZILDI
 * 4 MAYIS 2008 3         : TUM TABLOLAR UZERINDEN ISLEM YAPABILECEK SILME FONKSIYONU YAZILDI
 * 5 MAYIS 2008 1:        : ebat_listele() fonksiyonu yazılıp calistridili
 * 5 MAYIS 2008 2:        : ebat_ekle() fonksiyonu yazılıp calistridili
 * 7 MAYIS 2008 1:        :  EBAT SILME BASARILDI
 * 7 MAYIS 2008 2:        : ANAEKRAN ARAYÜZÜ VE TEKLIF EKLEME EDITORU (DIA_TEKLIF_EDITORU) OLUSTURULDU
 * 7 MAYIS 2008 3:        : TEKLIF EKLEME SISTEMI TAMAMLANDI
 * 7 MAYIS 2008 4:        : TEKLIF GUNCELLEME FORMU VERI SECIMI VE YANSITMASI TAMAMLANDI
 * 7 MAYIS 2008 5:          TEKLIG GUNCELLEME ISLEMI BASARIYLA TAMAMLANDI
 * 8 MAYIS 2008 1:          TEKLIFE BAGLI EBAT VERISI LISTELEME VE YENI EBAT EKLEME,EBAT SILME ISLEMI TAMAMLANDI
 * 8 MAYIS 2008 2:          LOG DOSYASI HER ACILISTA TEMIZLEYEN KOD YAZILDI
 * 13MAYIS 2008 1:          RAPORLAMA ISLEMI TAMAMLANDI
 * 13MAYIS 2008 2:          IKON VE ARAYUZLER DUZENLENDI
 * 13MAYIS 2008 3:          1.0 BETA YAYINLANDI
 * --------------------------------------------------------------------------------
 * 
 * ÖNTANIMLI GÖREVLERE GÖRE YAPILANLAR
 * ok-GOREV: TEKLIF SILININCE BAGLI EBATLARINDA SILINMESININI SAGLAYACAK KOD DUZENLENECEK-OK 08 MAYIS 2008
 * ok-TUM EBAT VERILERINI LISTELEYEN KOD YAZILACAK-OK
 * ok-TEKLIFE BAGLI EBATLAR EKRANINA TEKLIF VERILERI YANSITILACAK-OK (TABLO3 OLARAK YANSITILDI) 08 MAYIS 2008
 * ok-RAPORLAMA ISLEMI YAPILACAK-OK 13 MAYIS 2008
 * TODO :EBAT SILME YAPILDIGINDA AYNI ANDA TABLONUN GUNCELLENMESI SAGLANACAK
 * ok-TEKLIF_TARIHI SORUNU- COZULDU-OK 08 MAYIS 2008
 * ok-BIRIMFIYATLAR.INI DOSYASININ BEYIN DIZININDEN OKUNMASI SAGLANACAK-OK 08 MAYIS 2008
 * 
 * TODO INTERNETTEN AKTIVASYON YAPACAK KODLAR VE PROGRAM INSTRALLERI HAZIRLANACAK, EXE VEYA JAR OLABILIR 
 * TODO INSTALLER'E BASIT SES VE ETKILEYICI BIR GRAFIK KONACAK
 * TODO PROGRAMI ISTENDIGINDE SHAREWARE ISTENDIGINDE FREEWARE YAPACAK KODLAR YAZILACAK
 * TODO PROGRAMIN CESITLI YERLERINE SUATATAN IBARESI VE SAYFA ADRESI KONULACAK
 * OK-MENU VE KISAYOLLAR YAZILACAK
 * OK-BIRIMFIYAT KONFIGURASYONUNU ANA MENUDEN CAGIRMAK ICIN MENU EKLENECEK
 * TODO MOCAWA ICIN WEB SAYFASI YAPILACAK 
 * TODO HSQLDB SITESINE HSQLDB ILE YAZILMIS PROGRAMLAR OLRAK MOCAWA DA EKLENECEK
 * 
 * GELECEK SURUMLERDE DUSUNULENLER
 * TODO INTERNETE YEDEKLEME YAPACAK VE YEDEKLEMYI TEKRAR INDIRECEK
 * TODO MAIL ILE MUSTERILERE TEKLIF GONDERECEK
 * TODO BIRIM FIYATLA ADEDI CARPARAK GERCEK TUTAR OLUSTURACAK
 * TODO SOURCEFORGE VEYA DEV.JAVA.NET 'E KAYIT YAPILACAK
 * TODO CVS SISTEMI OLUSTURULACAK
 * TODO PROGRAM TUTARSA ONLINE SATIS SISTEMI KURULACAK
 * TODO BAZI FIRMALARA BEDAVA YOLLANACAK YA DA BIR YILLIK LISANS ILE
 *
 * 
 * 

 * 
 */


package mocawa_hsqldb_101_2;

import licencor.lisans_kontrol;


public class Main implements global.global_variables {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args)  {
   
        try {
            
             ana.setSize(1275,800); 
       
       
             if(lis.program_lisansli_mi()){
             ana.setVisible(true);//ANEKRAN ACILIYOR
             }
             else             {
                 
                 serialekrani.setVisible(true);
             }
       
            
        } catch (Exception e) {
            //HATA DURUMUNDA HATA EKRANININ AÇIYORUZ ve hatayı ekrana yazdırıyoruz
            hata.hatamesajiac(e);
            
            
            
        }
      
        
       
       
    }

}
