/*
 * entercode.java
 *
 * Created on 18 Mayıs 2008 Pazar, 23:50
 */

package licencor;

/**
 *
 * @author  Suat ATAN
 */
public class serialekrani extends javax.swing.JFrame {

    /** Creates new form entercode */
    public serialekrani() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PAN_SERIAL = new javax.swing.JPanel();
        LB_LISANS_1 = new javax.swing.JLabel();
        LB_LISANS_2 = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        LB_LISANS_3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        PAN_SERIAL.setBackground(new java.awt.Color(255, 255, 255));

        LB_LISANS_1.setText("Dikkat: Bu programın ücretli veya ücretsiz olarak dağıtımı üreticisi insiyatifindedir. ");

        LB_LISANS_2.setText("Lisans edinmek için suatatan@gmail.com adresine e-posta atabilirsiniz.");

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ustlogo.png"))); // NOI18N

        LB_LISANS_3.setForeground(new java.awt.Color(255, 51, 0));
        LB_LISANS_3.setText("PROGRAMI KULLANABİLMEK İÇİN LİSANS YAPTIRMALISINIZ.");

        javax.swing.GroupLayout PAN_SERIALLayout = new javax.swing.GroupLayout(PAN_SERIAL);
        PAN_SERIAL.setLayout(PAN_SERIALLayout);
        PAN_SERIALLayout.setHorizontalGroup(
            PAN_SERIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAN_SERIALLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PAN_SERIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_LISANS_3)
                    .addComponent(LB_LISANS_2)
                    .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_LISANS_1))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        PAN_SERIALLayout.setVerticalGroup(
            PAN_SERIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAN_SERIALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOGO)
                .addGap(32, 32, 32)
                .addComponent(LB_LISANS_3)
                .addGap(18, 18, 18)
                .addComponent(LB_LISANS_1)
                .addGap(18, 18, 18)
                .addComponent(LB_LISANS_2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(PAN_SERIAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serialekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_LISANS_1;
    private javax.swing.JLabel LB_LISANS_2;
    private javax.swing.JLabel LB_LISANS_3;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel PAN_SERIAL;
    // End of variables declaration//GEN-END:variables

}
