/*
 * hataekrani.java
 *
 * Created on 08 Mayıs 2008 Perşembe, 18:26
 */

package mocawa_hsqldb_101_2;

/**
 *
 * @author  Suat ATAN
 */
public class hataekrani extends javax.swing.JFrame {

    /** Creates new form hataekrani */
    public hataekrani() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LB_HATAOLUSTU = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EXCEPTION_PAD = new javax.swing.JTextArea();
        HATE_EKRANI_TAMAM = new javax.swing.JButton();
        LB_HATA_BILDIRIM1 = new javax.swing.JLabel();
        LB_HATA_BILDIRIM2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HATA EKRANI");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        LB_HATAOLUSTU.setText("PROGRAM AÇILIRKEN BİR HATAYLA KARŞILAŞTI,LÜTFEN 5 DK.SONRA PROGRAMI TEKRAR AÇINIZ.");

        EXCEPTION_PAD.setColumns(20);
        EXCEPTION_PAD.setRows(5);
        jScrollPane1.setViewportView(EXCEPTION_PAD);

        HATE_EKRANI_TAMAM.setText("TAMAM");
        HATE_EKRANI_TAMAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HATE_EKRANI_TAMAMMouseClicked(evt);
            }
        });

        LB_HATA_BILDIRIM1.setText("LÜTFEN YUKARIDAKİ MESAJI KOPYALARAYRAK PROGRAM GELİŞTİRİCİSİNE GÖNDERİNİZ. ");

        LB_HATA_BILDIRIM2.setText("PROGRAM GELİŞTİRİCİSİNE AİT İLETİŞİM EPOSTASI: suatatan@gmail.com");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                            .addComponent(LB_HATAOLUSTU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LB_HATA_BILDIRIM1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(HATE_EKRANI_TAMAM))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LB_HATA_BILDIRIM2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(LB_HATAOLUSTU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_HATA_BILDIRIM1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_HATA_BILDIRIM2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HATE_EKRANI_TAMAM)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void HATE_EKRANI_TAMAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HATE_EKRANI_TAMAMMouseClicked
// TODO add your handling code here:
    System.exit(0);
    
}//GEN-LAST:event_HATE_EKRANI_TAMAMMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hataekrani().setVisible(true);
            }
        });
    }

    public void hatamesajiac(Exception ex) {
      //  throw new UnsupportedOperationException("Not yet implemented");
        String hata=ex.toString();
       EXCEPTION_PAD.setText(hata);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea EXCEPTION_PAD;
    private javax.swing.JButton HATE_EKRANI_TAMAM;
    private javax.swing.JLabel LB_HATAOLUSTU;
    private javax.swing.JLabel LB_HATA_BILDIRIM1;
    private javax.swing.JLabel LB_HATA_BILDIRIM2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
